version: '3.9'

services:
  db:
    container_name: postgres-db
    build:
      dockerfile: Dockerfile
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1999
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/tdl